# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 480)
        Dialog.setStyleSheet("QLabel{font-size: 30px; font-family: \'Arial\';}\n"
"")
        self.HOME_icon = QtWidgets.QLabel(Dialog)
        self.HOME_icon.setGeometry(QtCore.QRect(310, 0, 161, 131))
        self.HOME_icon.setStyleSheet("QLabel#HOME_icon {\n"
"    border-image: url(:/home/home.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.HOME_icon.setText("")
        self.HOME_icon.setObjectName("HOME_icon")
        self.HOME_text = QtWidgets.QLabel(Dialog)
        self.HOME_text.setGeometry(QtCore.QRect(300, 140, 211, 61))
        self.HOME_text.setObjectName("HOME_text")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 240, 651, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_navigation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_navigation.setStyleSheet("QPushButton{font-size: 24px; font-family: \'Arial\';}\n"
"QPushButton:hover {\n"
"background-color: skyblue;\n"
"}")
        self.pushButton_navigation.setObjectName("pushButton_navigation")
        self.horizontalLayout.addWidget(self.pushButton_navigation)
        self.pushButton_receipt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_receipt.setStyleSheet("QPushButton{font-size: 24px; font-family: \'Arial\';}\n"
"QPushButton:hover {\n"
"background-color: skyblue;\n"
"}")
        self.pushButton_receipt.setObjectName("pushButton_receipt")
        self.horizontalLayout.addWidget(self.pushButton_receipt)

        self.pushButton_identification = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_identification.setStyleSheet("QPushButton{font-size: 24px; font-family: \'Arial\';}\n"
                                              "QPushButton:hover {\n"
                                              "background-color: skyblue;\n"
                                              "}")
        self.pushButton_identification.setObjectName("pushButton_identification")
        self.horizontalLayout.addWidget(self.pushButton_identification)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.HOME_text.setText(_translate("Dialog", "HOME (환자용)"))
        self.pushButton_navigation.setText(_translate("Dialog", "길찾기"))
        self.pushButton_receipt.setText(_translate("Dialog", "접수"))
        self.pushButton_identification.setText(_translate("Dialog", "신분증 찾기"))
import home_rc
